node {
  stage('Get latest commit on a private repo') {  
    sshagent (credentials: ['github-jerrys-private-key']) {
      // get the last commit id from a repository you own
      sh 'git ls-remote -h --refs git@github.com:jerryshikanga/usalama.git master |awk "{print $1}"'
    }
  }
}
